from pathlib import Path

source_path = Path("src/intelligence/transaction_decision_brief.py")
source = source_path.read_text(encoding="utf-8")

old_import = """    SourceReference,\n    TradeRiskSignal,\n)\n"""
new_import = """    SourceReference,\n    TradeFinanceDomainState,\n    TradeRiskSignal,\n)\n"""
if old_import not in source:
    raise SystemExit("transaction decision brief import anchor not found")
source = source.replace(old_import, new_import, 1)

old_apply = '''def apply_transaction_decision_brief(\n    case: UnifiedCopilotCase,\n    request: TransactionDecisionBriefRequest,\n    *,\n    registry_path: str | Path | None = None,\n) -> tuple[UnifiedCopilotCase, TransactionDecisionBrief, TransactionDecisionBriefOutcome]:\n    """Attach the current transaction action plan while preserving other case actions."""\n\n    brief = build_transaction_decision_brief(\n        case,\n        request,\n        registry_path=registry_path,\n    )\n    retained_actions = [\n        item\n        for item in case.trade_finance.action_plan\n        if not (\n            item.source.source_id == brief.source.source_id\n            and item.action_id.startswith(f"ACTION-{request.transaction_id}-")\n        )\n    ]\n    updated_domain = case.trade_finance.model_copy(\n        update={"action_plan": retained_actions + brief.action_plan}\n    )\n    updated_case = case.model_copy(update={"trade_finance": updated_domain})\n    outcome = TransactionDecisionBriefOutcome(\n        case_before_hash=case.case_hash,\n        case_after_hash=updated_case.case_hash,\n        brief_id=request.brief_id,\n        transaction_id=request.transaction_id,\n        disposition=brief.disposition,\n        action_ids=[item.action_id for item in brief.action_plan],\n        missing_information=brief.missing_information,\n    )\n    return updated_case, brief, outcome\n'''
new_apply = '''def _renumber_action_plan(actions: list[ActionPlanItem]) -> list[ActionPlanItem]:\n    """Return a globally ordered action plan with unique consecutive sequences."""\n\n    return [\n        item.model_copy(update={"sequence": sequence})\n        for sequence, item in enumerate(actions, start=1)\n    ]\n\n\ndef apply_transaction_decision_brief(\n    case: UnifiedCopilotCase,\n    request: TransactionDecisionBriefRequest,\n    *,\n    registry_path: str | Path | None = None,\n) -> tuple[UnifiedCopilotCase, TransactionDecisionBrief, TransactionDecisionBriefOutcome]:\n    """Attach the current transaction action plan while preserving other case actions."""\n\n    brief = build_transaction_decision_brief(\n        case,\n        request,\n        registry_path=registry_path,\n    )\n    retained_actions = [\n        item\n        for item in case.trade_finance.action_plan\n        if not item.action_id.startswith(f"ACTION-{request.transaction_id}-")\n    ]\n    combined_actions = _renumber_action_plan(retained_actions + brief.action_plan)\n    combined_by_id = {item.action_id: item for item in combined_actions}\n    brief = brief.model_copy(\n        update={\n            "action_plan": [\n                combined_by_id[item.action_id] for item in brief.action_plan\n            ]\n        }\n    )\n    domain_payload = case.trade_finance.model_dump(mode="python")\n    domain_payload["action_plan"] = combined_actions\n    updated_domain = TradeFinanceDomainState.model_validate(domain_payload)\n    updated_case = case.model_copy(update={"trade_finance": updated_domain})\n    outcome = TransactionDecisionBriefOutcome(\n        case_before_hash=case.case_hash,\n        case_after_hash=updated_case.case_hash,\n        brief_id=request.brief_id,\n        transaction_id=request.transaction_id,\n        disposition=brief.disposition,\n        action_ids=[item.action_id for item in brief.action_plan],\n        missing_information=brief.missing_information,\n    )\n    return updated_case, brief, outcome\n'''
if old_apply not in source:
    raise SystemExit("apply_transaction_decision_brief anchor not found")
source = source.replace(old_apply, new_apply, 1)
source_path.write_text(source, encoding="utf-8")

test_path = Path("tests/test_transaction_decision_brief.py")
tests = test_path.read_text(encoding="utf-8")
anchor = '''def test_max_ranked_concerns_limits_display_not_disposition_logic():\n'''
new_test = '''def test_apply_renumbers_actions_across_transactions_and_revalidates_domain():\n    case = _case()\n    case = case.model_copy(\n        update={\n            "approved_transactions": [\n                *case.approved_transactions,\n                {\n                    "transaction_id": "EXP-002",\n                    "transaction_type": "export",\n                    "currency": "USD",\n                    "amount_fc": 250000,\n                    "expected_date": "2026-12-15",\n                },\n            ]\n        }\n    )\n\n    first, _, _ = apply_transaction_decision_brief(case, _request(case))\n    second_request = _request(\n        first,\n        brief_id="BRIEF-EXP-002",\n        transaction_id="EXP-002",\n        product_candidate_ids=[],\n        consultation_requirement_ids=[],\n    )\n    second, second_brief, _ = apply_transaction_decision_brief(\n        first,\n        second_request,\n    )\n\n    action_plan = second.trade_finance.action_plan\n    assert [item.sequence for item in action_plan] == list(\n        range(1, len(action_plan) + 1)\n    )\n    assert len({item.action_id for item in action_plan}) == len(action_plan)\n    assert any(item.action_id.startswith("ACTION-EXP-001-") for item in action_plan)\n    assert any(item.action_id.startswith("ACTION-EXP-002-") for item in action_plan)\n\n    attached_by_id = {item.action_id: item for item in action_plan}\n    assert all(attached_by_id[item.action_id] == item for item in second_brief.action_plan)\n    reloaded = UnifiedCopilotCase.model_validate(second.model_dump(mode="python"))\n    assert reloaded.case_hash == second.case_hash\n\n    third, third_brief, _ = apply_transaction_decision_brief(\n        second,\n        second_request,\n    )\n    assert third.case_hash == second.case_hash\n    assert third_brief.model_dump(mode="json") == second_brief.model_dump(mode="json")\n\n\n'''
if anchor not in tests:
    raise SystemExit("test insertion anchor not found")
tests = tests.replace(anchor, new_test + anchor, 1)
test_path.write_text(tests, encoding="utf-8")
